/* =========================================================
   ASSETS
========================================================= */

export const noorPediaAssets = {
  hero: "https://www.noorcapital.ae/images/platform/platform-banner.png",

  background: "https://www.noorcapital.ae/images/services/pattern-bg.png",

  arrowUp: "https://www.noorcapital.ae/images/icons/arrowUp.svg",
};

/* =========================================================
   SOURCE GLOSSARY — EXACT ENGLISH COPY
========================================================= */

export const noorPediaGlossary = [
  {
    term: "Day Trade",
    definition:
      "When traders place an opening and closing trade on the same stock on the same day, they are making a day trade and are subject to special rules.",
  },

  {
    term: "Professional Day Trader",
    definition:
      "A professional day trader can informally be considered somebody who day trades for a living.",
  },

  {
    term: "Swing Trading",
    definition:
      "Swing traders will hold stocks for at least one night. These are very short-term investments.",
  },

  {
    term: "Bull or Bullish",
    definition: "This term refers to a strong market of stocks moving up.",
  },

  {
    term: "Bear or Bearish",
    definition:
      "This term refers to a weak market; this means traders think the price of stocks or a specific stock will be going down.",
  },

  {
    term: "Initial Public Offering (IPO)",
    definition:
      "When a company floats an IPO, they sell a fixed number of shares of a particular company in the open market to raise money.",
  },

  {
    term: "Float",
    definition:
      "Float refers to the number of outstanding shares available for trade.",
  },

  {
    term: "Share Buy Back",
    definition:
      "A Share Buy Back program is when a company buys back shares that were sold during the IPO. By doing this, they are reducing the number of shares available for trading purposes in the market.",
  },

  {
    term: "Secondary Offering",
    definition:
      "A secondary offering is an offering that is given after the Initial Public Offering. A secondary offering will raise money for the company by selling more shares.",
  },

  {
    term: "Beta",
    definition:
      "Beta is a measure of the volatility—or systematic risk—a security or portfolio compared to the market as a whole.",
  },

  {
    term: "Crossed Market",
    definition:
      "A crossed market refers to a temporary situation where the bid price associated with a particular asset or security is higher than the ask price.",
  },

  {
    term: "Dividend",
    definition:
      "Dividends are the money paid out to shareholders who hold shares of the company for a certain period of time as a way of sharing the company's success.",
  },

  {
    term: "Divergence",
    definition:
      "In day trading, divergence is trading concept that forms on your trading bar chart and results from the price action of security moving in opposite directions.",
  },

  {
    term: "Earnings Per Share",
    definition:
      "Earnings Per Share (EPS) is a portion of a company's profit allocated to a person's stock share and is an essential metric for analysts.",
  },

  {
    term: "Market Cap",
    definition:
      "Market Capitalization is a measurement used to classify a company's size and is based on the market value of the total shares outstanding.",
  },

  {
    term: "Merger",
    definition:
      "Mergers are deals that unite two separate companies into a single new business entity.",
  },

  {
    term: "Penny Stocks",
    definition:
      "A penny stock typically refers to the stock of a small companies.",
  },

  {
    term: "Return on Investment (ROI)",
    definition:
      "Return on investment (ROI) is a metric that measures profit or loss generated by an investment about the invested funds.",
  },

  {
    term: "Shares Outstanding",
    definition:
      "Shares outstanding refers to the stock of a company currently held by all shareholders, including restricted and institutional shares.",
  },

  {
    term: "Market Trend",
    definition:
      "Market trend represents the general direction in a market or security over a given period of time and can last from a couple of days to many months or years.",
  },

  {
    term: "Volatility",
    definition:
      "This refers to the level of uncertainty surrounding price fluctuations of financial instruments. Volatility is usually characterized by rapid, random price movements.",
  },

  {
    term: "Support Level",
    definition:
      "A professional day trader can informally be considered somebody who day trades for a living.",
  },

  {
    term: "Resistance Level",
    definition:
      "A resistance level is the price level at which the selling of a security is deemed healthy enough to eliminate the price increase.",
  },

  {
    term: "Stock",
    definition:
      "Stock is a type of asset that gives you ownership in a company, allowing you to claim the company's assets and earnings.",
  },

  {
    term: "Price Target",
    definition:
      "A price target is the projected price of a financial instrument provided by an analyst and used to determine under and overvalued stocks.",
  },

  {
    term: "Recession",
    definition:
      "Recession refers to when a country's economy experiences a decline due to different factors over a specific period.",
  },

  {
    term: "OTC Market",
    definition:
      "The OTC or over-the-counter market allows for the trading of assets without the formal structure of official exchange and is considered risky.",
  },

  {
    term: "Hard To Borrow",
    definition:
      "The Hard to borrow list refers to an inventory of securities the brokerage firm cannot provide for short selling and is only available for buying.",
  },

  {
    term: "Derivative",
    definition:
      "Derivatives are securities with prices dependent on, or derived from, one or more separate underlying assets such as options or futures contracts.",
  },

  {
    term: "Equity",
    definition:
      "Equity refers to the ownership of assets after liabilities and debts have been settled, or it can refer to stock or ownership of shares in a public company.",
  },

  {
    term: "Blue Chip",
    definition:
      "Blue-chip stocks are companies that are often worth billions of dollars, pay dividends, and have a long history of reliable operations.",
  },

  {
    term: "Bond",
    definition:
      "A bond is a debt investment where investors loan funds to a corporate or government for a particular period of time at a variable or fixed interest rate.",
  },

  {
    term: "Long Side Trading",
    definition:
      'When traders are "long" a stock, they are buying shares and expect the stock price to go up.',
  },

  {
    term: "Price Average",
    definition:
      "Price average is the average price of the stock that you have paid.",
  },

  {
    term: "Short Side Trading",
    definition:
      'glossTraders who are "short" on a stock are short-selling shares. As soon as they sell the shares, they profit from the sale; however, they must buy back the shares.ary5',
  },

  {
    term: "Borrowing",
    definition:
      "You must borrow shares from your broker to short. If your broker doesn't have shares available for you to borrow, you can't short the stock.",
  },

  {
    term: "Covering",
    definition:
      'To close a short position, a trader must "cover" their position, this is, buying stocks to cover the shares they borrowed from their broker.',
  },

  {
    term: "Short Interest",
    definition:
      "Short interest refers to the number of shares all traders worldwide are currently holding as a short position against the stock.",
  },

  {
    term: "Short Squeeze",
    definition:
      "This is when a stock suddenly starts moving up, and traders holding short positions start buying to cover their positions.",
  },

  {
    term: "Margin",
    definition:
      "When a trader opens a broker account, they are given Margin. In addition to allowing you to trade on borrowed money, they also extend a line of credit to your account for trading.",
  },

  {
    term: "Leverage Rate",
    definition:
      "The rate that your cash deposit will be multiplied to give you total buying power.",
  },

  {
    term: "Buying Power",
    definition:
      "The money an investor has for purchasing securities, the cash balance plus the margin.",
  },

  {
    term: "Margin Rate",
    definition:
      "The percentage a trader has to pay their broker in exchange for borrowing money.",
  },

  {
    term: "Margin Call",
    definition:
      "Traders who are issued a margin call are in debt to their broker. The broker will require you to repay the debt and force you to sell other assets to return the money.",
  },

  {
    term: "Bid Price",
    definition:
      "Bid Price is the price at which traders are currently bidding on stock.",
  },

  {
    term: "Ask Price",
    definition:
      "Ask price is the price at which traders are currently asking to sell the stock.",
  },

  {
    term: "Spread",
    definition: "Spread is the difference between the Bid price and Ask price.",
  },

  {
    term: "Market makers",
    definition:
      "Market Makers create the spread. They are large institutional players that are both buyers and sellers of a stock.",
  },

  {
    term: "Volume",
    definition: "Volume is a measure of the number of shares traded.",
  },

  {
    term: "Relative volume",
    definition:
      "Relative volume shows how much volume a stock has compared to its average volume for the same period.",
  },

  {
    term: "A Thin Market",
    definition:
      "Thin market means a low number of traders actively trade a particular stock. In a thin market, prices tend to be volatile.",
  },

  {
    term: "A Thick Market",
    definition:
      "Thickly-traded markets and stocks will be crowded with traders.",
  },

  {
    term: "Circuit Breaker",
    definition:
      "Stocks can be halted and paused from trading for several reasons. During circuit-breaker halts, traders cannot trade the stock in any way.",
  },

  {
    term: "Slippage",
    definition:
      "Slippage is the difference between the price you thought you would trade at and the price at which the trade went through.",
  },

  {
    term: "Limit Orders",
    definition:
      "A limit order is when you ask your broker to buy you shares and state the most you are willing to pay.",
  },

  {
    term: "Stop Orders",
    definition:
      "Stop orders are a versatile order used for getting in and out of trades. When you place a stop order, you are saying that you want to get in or out of a trade when prices hit your stop price.",
  },

  {
    term: "FOK Order",
    definition:
      "This is Fill or Kill, which means either you get your entire order filled or the order won't fill at all; this prevents partial orders.",
  },

  {
    term: "GTC Order",
    definition:
      "This is a Good Till Cancelled order. That means the order will stay on the broker's servers until you cancel it.",
  },

  {
    term: "Trailing Stop",
    definition:
      "Trailing stop order is a stop order that allows setting of the value as a percentage usually below the current market price and will move as prices move.",
  },

  {
    term: "Good Till Cancelled",
    definition:
      "A Good Till Cancelled (GTC) order refers to a buy or sell request designed to last until the request is executed or canceled by the trader or broker.",
  },

  {
    term: "Fundamental Analysis",
    definition:
      "Fundamental Analysis is when a trader (or more often, an investor) looks at a company's fundamental metrics. This includes their annual and quarterly earnings per share, their book value (total value of company assets), their sector's strength, and the growth potential.",
  },

  {
    term: "Technical Analysis",
    definition:
      "Technical Analysis, in contrast to fundamental analysis, focuses solely on the stock price.",
  },

  {
    term: "Line Charts",
    definition:
      "Line charts simply plot a line. This can give a good understanding of price action over long periods of time, but it doesn't provide the necessary insight that traders require for shorter time periods.",
  },

  {
    term: "Bar Charts",
    definition:
      "Bar charts show the open price and the close price for any given period.",
  },

  {
    term: "Candlestick Charts",
    definition:
      "Candlestick charts include four pieces of information. The open price, the close price, the high of the period price, and the low of the period price.",
  },

  {
    term: "Technical Indicators",
    definition:
      "Technical indicators, or studies, help us interpret current price action.",
  },

  {
    term: "Moving Averages",
    definition:
      "Moving averages are a technical indicator that tells us the average price of a stock over time.",
  },

  {
    term: "Simple Moving Average",
    definition:
      "Simple Moving Average (SMA) is an average price calculation on the closing price of a security over a period of time divided by the number of periods.",
  },

  {
    term: "Volume Profile",
    definition:
      "The volume profile refers to an advanced charting study used to show trading activity where volume is displayed at prices instead of over a specific time.",
  },

  {
    term: "Standard Deviation",
    definition:
      "Standard deviation is a statistical measure representing the rate of divergence from the mean in a data set and is used a lot in trading.",
  },

  {
    term: "On Balance Volume",
    definition:
      "On Balance Volume, a momentum indicator helps measure the buying and selling pressure in a stock or any other financial security with volume.",
  },

  {
    term: "Opening Range Breakout",
    definition:
      "An opening range breakout is a relatively simple strategy that involves taking a position when price breaks above or below the previous candle, high or low.",
  },

  {
    term: "Keltner Channel",
    definition:
      "The Keltner Channel is a technical indicator that shows a central line for a moving average and channel lines below and above.",
  },

  {
    term: "Average Directional Index (ADX)",
    definition:
      "Average Directional Index is a technical indicator used to signify the strength of a trend and works best when a stock is trending.",
  },
];

/* =========================================================
   PAGE COPY
========================================================= */

const en = {
  hero: "Noor Pedia",

  glossaryTitle: "TRADER'S GLOSSARY",

  backTop: "Back to top",
};

const tr = {
  hero: "Noor Pedia",

  glossaryTitle: "YATIRIMCI SÖZLÜĞÜ",

  backTop: "Yukarı dön",
};

const ru = {
  hero: "Noor Pedia",

  glossaryTitle: "СЛОВАРЬ ТРЕЙДЕРА",

  backTop: "Наверх",
};

const ar = {
  hero: "Noor Pedia",

  glossaryTitle: "قاموس المتداول",

  backTop: "العودة للأعلى",
};

export const noorPediaCopy = {
  en,
  tr,
  ru,
  ar,
};
